# <copyright_statement>
#   CodeBuddy - computing-education software
#   Copyright (C) 2023 Stephen Piccolo
#   This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
# </copyright_statement>

description: Please write a bash script based on the instructions provided.
memory_allowed_mb: 500
timeout_seconds: 60
code_completion_path: ace/mode/sh
output_types:
    txt: |-
        Text (standard out)
solution_instructions: ""
solution_example: |
    mkdir Assignment1
    cd Assignment1
    touch newfile
    ls
verification_instructions: "Write your verification code in bash."
verification_example: |
    #!/bin/bash

    # Set the pattern to search for
    pattern="xyz"

    # Check if the pattern exists in the file
    if grep -q "$pattern" "code"; then
        echo "Error: You are not allowed to use '$pattern' in your solution."
    fi
test_instructions: ""
after_test_example: ""