# <copyright_statement>
#   CodeBuddy - computing-education software
#   Copyright (C) 2023 Stephen Piccolo
#   This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
# </copyright_statement>

description: Please write C++ code based on the instructions provided.
memory_allowed_mb: 500
timeout_seconds: 60
code_completion_path: ace/mode/c_cpp
output_types:
    txt: |-
        Text
solution_instructions: ""
solution_example: |
    #include <iostream>

    int add_numbers(int a, int b) {
        return a + b;
    }
verification_instructions: "Write your verification code in C++."
verification_example: |
    #include <iostream>
    #include <fstream>
    #include <string>

    int main() {
        std::ifstream file("code");
        std::string line;
        std::string pattern = "xyz"; // Change this to the desired pattern

        if (!file.is_open()) {
            std::cerr << "Failed to open the code file to verify it." << std::endl;
            return 1;
        }

        while (getline(file, line)) {
            if (line.find(pattern) != std::string::npos) {
                std::cout << "You are not allowed to use '" + pattern + "' in your solution." << line << std::endl;
                break; // Stop executing further if pattern is found
            }
        }

        file.close();

        return 0;
    }
test_instructions: ""
after_test_example: |
    int main() {
        int num1 = 2;
        int num2 = 3;
        int result = add_numbers(num1, num2);
        
        std::cout << "The sum is: " << result << std::endl;
        
        return 0;
    }