#! /bin/bash

set -o errexit

current_dir="$(pwd)"

for container_dir in ${current_dir}/back_ends/*
do
  image_name=srp33/codebuddy_$(basename ${container_dir})

  cd ${container_dir}

  cp ${current_dir}/exec_back_end.sh ${container_dir}/exec.sh

  docker build -t ${image_name} -f Containerfile .
done
