#! /bin/bash

mkdir -p course

# Use this if you want to run the front end on your local computer
#./run_container front_end "-p 9001:9001 -e NUM_PROCESSES=4 -e PORT=9001 -v $(pwd)/course:/course -v $(pwd)/data:/data -v /tmp:/tmp" ""

# Use this if you want to be able to run front end and back end on a Linux server
./run_container front_end "--network host -e NUM_PROCESSES=4 -e PORT=9001 -v $(pwd)/course:/course -v $(pwd)/data:/data -v /tmp:/tmp" ""


##--tmpfs /tmp
