#! /bin/bash

subdir_name="$1"
run_args="$2"
tag="$3"

if [[ "${subdir_name}" == "" ]]
then
  echo "No subdirectory name was specified."
  exit 1
fi

if [[ "${tag}" == "" ]]
then
  tag=version$(cat VERSION)
fi

#docker rm $(docker stop $(docker ps -a -q --filter ancestor=${image_name} --format="{{.ID}}") 2> /dev/null) 2> /dev/null
docker container stop ${subdir_name} 2> /dev/null

set -o errexit

image_name=srp33/codebuddy_${subdir_name}

docker build -t ${image_name} -f ${subdir_name}/Containerfile .

#docker run -d \
docker run -i -t \
  --rm \
  --read-only \
  --name ${subdir_name} \
  ${run_args} \
  ${image_name}

#--name=name
#--security-opt=option
#  no-new-privileges
#-u=user
