#! /bin/bash

mkdir -p course data logs/summarized logs/archive submissions

# Use this if you want to run the front end on your local computer
#./run_container front_end "-p 9001:9001 -e NUM_PROCESSES=4 -e PORT=9001 -v $(pwd)/course:/course -v $(pwd)/data:/data -v /tmp:/tmp -v $(pwd)/logs:/logs" ""

# Use this if you want to be able to run front end and back end on a Linux server
./run_container front_end "--user $(id -u):$(id -g) --network host -e NUM_PROCESSES=4 -e PORT=8008 -e MPORT=9799 -v $(pwd)/course:/course -v $(pwd)/data:/data -v $(pwd)/submissions:/submissions -v /tmp:/tmp -v $(pwd)/logs:/logs" ""


##--tmpfs /tmp
