#! /bin/bash

set -o errexit

./build_back_ends

export PATH=$PATH:~/.local/bin

cd middle_layer

#uvicorn main:app --port 9798 --workers 4
gunicorn main:app -b 127.0.0.1:9798 -w 4 -k uvicorn.workers.UvicornWorker
