FROM continuumio/miniconda3

#ENV USER codebuddy

RUN apt-get update \
 && apt-get install -y bzip2 zip \
 && apt-get -y autoremove \
 && apt-get clean \
 && conda install -y tornado requests PyYAML arrow Pillow markdown2 \
 && mkdir -p /app /conda /course /static
 && wget -O /static/jquery.min.js https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js \
 && curl https://raw.githubusercontent.com/jenil/bulmaswatch/gh-pages/flatly/bulmaswatch.min.css | sed -En 's/.footer\{background-color:#ecf0f1;padding:3rem 1.5rem 6rem\}/.footer\{background-color:#ecf0f1;padding:1rem 3.0rem 1rem\}/p' > /static/bulmaswatch.min.css \
 && curl https://raw.githubusercontent.com/CreativeBulma/bulma-tooltip/master/dist/bulma-tooltip.min.css > /static/bulma-tooltip.min.css \
 && git clone https://github.com/ajaxorg/ace-builds.git \
 && cp -r ace-builds/src-min-noconflict/* /static/

ADD *.yaml /
ADD VERSION /
ADD front_end/summarize_logs.sh /etc/cron.hourly/
ADD front_end/ace-builds/src-min-noconflict /static/
ADD front_end/*css* /static/
ADD front_end/*.js /static/
ADD front_end/*.png /static/
ADD front_end/favicon.ico /static/
ADD front_end/site.webmanifest /static/
ADD front_end/build_html.sh /app/
ADD front_end/startup.sh /app/
ADD front_end/html/* /tmp/
ADD front_end/*.py /app/

RUN bash /app/build_html.sh

#RUN groupadd -r $USER \
# && useradd -r -s /bin/false -g $USER $USER \
# && chown -R $USER:$USER /app /conda /course /tmp/img /static \
# && chmod -R 400 /app /conda \
# && chmod -R 700 /course /img /static

#USER $USER
ENTRYPOINT ["bash", "/app/startup.sh"]
#ENTRYPOINT ["bash", "/etc/cron.hourly/summarize_logs.sh"]
