FROM rust:1.83-slim-bookworm AS builder

WORKDIR /app

# Create a dummy project to fetch dependencies
#RUN USER=root cargo new --bin myapp
RUN cargo new --bin myapp \
 && chmod 777 /app/myapp -R

WORKDIR /app/myapp

# Add the dependencies you need
COPY Cargo.toml /app/myapp/

# Pre-fetch the dependencies
RUN cargo fetch

RUN apt-get update \
 && apt-get install -y --no-install-recommends python3 \
 && rm -rf /var/lib/apt/lists/*

ADD *.py /
ADD *.sh /

ENTRYPOINT ["bash", "/exec.sh"]
