FROM rust:1.68.1-slim-bullseye as builder

WORKDIR /app

# Create a dummy project to fetch dependencies
#RUN USER=root cargo new --bin myapp
RUN cargo new --bin myapp \
 && chmod 777 /app/myapp -R

WORKDIR /app/myapp

# Add the dependencies you need
COPY Cargo.toml /app/myapp/

# Pre-fetch the dependencies
RUN cargo fetch

RUN apt-get update \
 && apt-get install python3 -y

ADD *.py /
ADD *.sh /

ENTRYPOINT ["bash", "/exec.sh"]
