FROM python:3.12.3-slim-bullseye

RUN apt-get update \
 && apt-get install build-essential git -y \
 && pip install --upgrade pip \
 && pip install seaborn==0.12.2 \
 && pip install sympy==1.12 \
 && pip install scipy==1.13.1 \
 && pip install imageio==2.34.1 \
 && git clone https://github.com/mwaskom/seaborn-data.git \
 && chmod 777 /seaborn-data -R \
 && pip install biopython==1.81

ENV MPLCONFIGDIR /tmp

ADD *.sh /
ADD *.py /

ENTRYPOINT ["bash", "/exec.sh"]
