FROM rocker/tidyverse:4.0.0

RUN apt-get update -qq && apt-get install -y \
  git-core \
  libssl-dev \
  libcurl4-gnutls-dev \
  libjemalloc-dev \
  libmagick++-dev

RUN R -e "install.packages(c('car', 'conflicted', 'igraph', 'magick', 'mapproj', 'maps', 'ranger', 'tidymodels', 'workflows', 'tune', 'XML'))"

ADD exec.R /

ENTRYPOINT ["Rscript", "--vanilla", "/exec.R"]
