# <copyright_statement>
#   CodeBuddy - computing-education software
#   Copyright (C) 2023 Stephen Piccolo
#   This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version. This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details. You should have received a copy of the GNU Affero General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
# </copyright_statement>

FROM python:3.9.1-slim-buster

RUN apt-get update \
 && apt-get install git -y \
 && pip install --upgrade pip \
 && pip install seaborn==0.12.2 \
 && git clone https://github.com/mwaskom/seaborn-data.git \
 && chmod 777 /seaborn-data -R

ENV MPLCONFIGDIR /tmp

ADD *.py /
ADD *.sh /

ENTRYPOINT ["bash", "/exec.sh"]
