FROM rocker/tidyverse:3.6.1

RUN apt-get update -qq && apt-get install -y \
  git-core \
  libssl-dev \
  libcurl4-gnutls-dev \
  libjemalloc-dev \
  libmagick++-dev

ADD r_back_end/libraries /
RUN R -e "packages <- c('plumber', scan('/libraries', what=character(), quiet=TRUE)); install.packages(packages)"

ADD r_back_end/*.R /
ENTRYPOINT ["Rscript", "/app.R"]
