FROM python:3.9.1-slim-buster

RUN apt-get update \
 && apt-get install git -y \
 && pip install --upgrade pip \
 && pip install seaborn==0.10.1 \
 && git clone https://github.com/mwaskom/seaborn-data.git \
 && chmod 777 /seaborn-data -R

ENV MPLCONFIGDIR /tmp

ADD *.py /
ADD *.sh /

ENTRYPOINT ["bash", "/exec.sh"]
